// Run with Node.js and jsdom available on NODE_PATH: node tests/app.test.cjs
const {JSDOM}=require('jsdom');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const root=path.resolve(__dirname,'..');
const code=fs.readFileSync(path.join(root,'app.js'),'utf8');const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
async function env(seed={}){const dom=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only'});const w=dom.window;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.confirm=()=>true;w.setInterval=()=>0;w.fetch=async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(root,url),'utf8'))});for(const [k,v]of Object.entries(seed))w.localStorage.setItem(k,v);w.eval(code+'\nwindow.testAccess={get:()=>({state,QUESTIONS,LABS,ALL}),start,submitAnswer,next,finish,tick,clean,save,home,renderQuestion,library,importData,choose:(n)=>{selected=n;document.querySelector(\'[name="confidence"][value="3"]\').checked=true;}};');await new Promise(r=>setTimeout(r,20));return {w,t:w.testAccess,close:()=>dom.window.close()};}
(async()=>{
 let e=await env({'gsec_ops_trainer_v02':JSON.stringify({xp:55,attempts:4,correct:2,mistakes:[1],confidentWrong:[1],domains:{Networking:{a:4,c:2}}})});let {w,t}=e;assert.equal(t.get().state.xp,55);assert(w.localStorage.getItem('gsec_ops_trainer_v02'));assert.equal(t.get().QUESTIONS.length,576);
 for(const mode of ['section','rapid','weak','boss','exam','timed']){t.start(mode);const s=t.get().state.session;assert.equal(new Set(s.ids).size,s.ids.length);assert.equal(s.ids.length,{section:40,rapid:25,weak:25,boss:25,exam:50,timed:106}[mode]);if(['exam','timed'].includes(mode))assert.equal(new Set(s.ids.map(id=>t.get().QUESTIONS.find(q=>q.id===id).section)).size,6);}
 for(const type of ['port','command','acronym']){w.document.querySelector('#rapidType').value=type;t.start('rapid');assert(t.get().state.session.ids.every(id=>t.get().QUESTIONS.find(q=>q.id===id).kind===type));}
 t.start('section');let s=t.get().state.session;let q=t.get().ALL.find(q=>q.id===s.ids[0]);let attempts=t.get().state.attempts;t.submitAnswer();assert.equal(t.get().state.attempts,attempts);t.choose((q.answer+1)%4);t.submitAnswer();assert(t.get().state.mistakes.includes(q.id));assert(t.get().state.confidentWrong.includes(q.id));t.submitAnswer();assert.equal(t.get().state.attempts,attempts+1);
 t.start('confident');s=t.get().state.session;assert(s.ids.includes(q.id));s.index=s.ids.indexOf(q.id);t.renderQuestion();t.choose(q.answer);t.submitAnswer();assert(!t.get().state.mistakes.includes(q.id));assert(!t.get().state.confidentWrong.includes(q.id));
 t.start('mission',t.get().LABS[0]);for(let i=0;i<6;i++){s=t.get().state.session;q=t.get().ALL.find(q=>q.id===s.ids[s.index]);t.choose(q.answer);t.submitAnswer();t.next();}assert.equal(t.get().state.labStats['1.1'].best,100);assert.equal(t.get().state.session,null);
 t.start('timed');s=t.get().state.session;assert.equal(s.deadline-s.started,14400000);q=t.get().ALL.find(q=>q.id===s.ids[0]);attempts=t.get().state.attempts;t.choose(q.answer);t.submitAnswer();assert.equal(t.get().state.attempts,attempts);assert(w.document.querySelector('#feedback').classList.contains('hidden'));s.flags=[0,5];t.save();const backup=w.localStorage.getItem('gsec_ops_trainer_v03');const deadline=s.deadline;const ids=[...s.ids];e.close();
 e=await env({'gsec_ops_trainer_v03':backup});({w,t}=e);s=t.get().state.session;assert.equal(s.deadline,deadline);assert.deepEqual([...s.ids],ids);assert.equal(s.flags[1],5);assert(s.responses[0]);s.deadline=Date.now()-1;t.tick();assert.equal(t.get().state.session,null);assert.equal(t.get().state.lastResult.correct,1);assert.equal(t.get().state.lastResult.expired,true);assert.equal(t.get().state.attempts,attempts+106);t.tick();assert.equal(t.get().state.attempts,attempts+106);
 const malformed=JSON.parse(backup);malformed.session.orders[0]=[0,0,1,2];assert.throws(()=>t.clean(malformed));const prior=t.get().state.xp;await t.importData({target:{files:[{size:8,text:async()=>'{invalid'}],value:'x'}});assert.equal(t.get().state.xp,prior);
 w.document.querySelector('#search').value='Kerberos';t.library();assert(w.document.querySelector('#searchCount').textContent.includes('matches'));assert(w.document.querySelector('#searchResults').children.length>0);e.close();
 e=await env({'gsec_ops_trainer_v03':'{corrupt'});assert.equal(e.w.localStorage.getItem('gsec_ops_trainer_v03'),'{corrupt');e.close();
 console.log('PASS: migration, all modes, unique sampling, section balance, drill filters, confidence-before-answer, no double scoring, remediation, lab scoring, exam delayed feedback, reload persistence, flags, expiry, unanswered scoring, import rejection, search, corrupt-state preservation.');
})().catch(e=>{console.error(e);process.exitCode=1;});
